version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.5
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - path.logs=/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - esdata:/usr/share/elasticsearch/logs
volumes:
  esdata:
    driver: local