version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.5
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - path.logs=/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - esdata:/usr/share/elasticsearch/logs
    networks:
     - docker_elk
     
  elastichq:
    image: polinux/elastichq
    environment:
      - HQ_DEFAULT_URL=HTTP://elasticsearch:9200
    ports:
      - "5000:5000"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - esdata:/usr/share/elasticsearch/logs
    networks:
      - docker_elk

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.5
    environment:
      - elasticsearch_url=HTTP://elasticsearch:9200
      - xpack.monitoring.enabled=false
      - xpack.monitoring.kibana.collection.enabled=false
      - xpack.monitoring.ui.enabled=false
    ports: 
      - "5601:5601"
    networks:
      - docker_elk
     
volumes:
  esdata:
    driver: local
    
networks:
  docker_elk:
    driver: bridge    

    
    